wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n

wsgi:
  host: labels.wmflabs.org
  application_root: ""
  url_prefix: ""
  cors_allowed: https\://([^\.\/]+\.)?(wiki[pm]edia|wikidata)\.org

database:
  host: localhost
  dbname: wikilabels

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  creds: oauth-wikimedia.yaml
