wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n

wsgi:
  host: labels.wmflabs.org
  application_root: ""
  url_prefix: ""

database:
  host: localhost
  dbname: wikilabels
  creds: wikilabels-db-config.yaml


oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  creds: oauth-wikimedia.yaml
